Contact_HR/Controllers/ContactController.cs
using Contact_HR.Models;
using Contact_HR.Models.DAO;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Contact_HR.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Escrever()
        {
            return View();
        }
        public ActionResult Consultar()
        {
            return View();
        }
        [HttpPost]
        public String ConsultarID(string messageKey)
        {
            CONTACT c = new CONTACT();
            CONTACTDAO dao = new CONTACTDAO();

            c = dao.getContactByKey(messageKey);

            ContactDTO cdto = new ContactDTO
            {
                id = c.id,
                message = c.message,
                response = c.response,
                readStatus = c.readStatus
            };

            return JsonConvert.SerializeObject(cdto);
        }
    }
}

Contact_HR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="~/Content/CSS/jquery.toastmessage.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/CSS/table-sorter.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/CSS/datepicker.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/CSS/app.css" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fale com a Flex", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Escrever", "Escrever", "Contact")</li>
                    <li>@Html.ActionLink("Consultar", "Consultar", "Contact")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Chique</p>
        </footer>
    </div>



    @RenderSection("scripts", required: false)

    <script type="text/javascript" src="~/Content/js/jquery.toastmessage.js"></script>
    <script type="text/javascript" src="~/Content/js/jquery.tablesorter.min.js"></script>
    <script type="text/javascript" src="~/Content/js/TableFilter/tablefilter.js"></script>
    <script type="text/javascript" src="~/Content/js/bootstrap-datepicker.js"></script>
</body>
</html>